"""reduce address fields to one address string field

Revision ID: 6d9401026a2e
Revises: 063ef5a541b7
Create Date: 2023-12-13 16:23:00.107877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d9401026a2e'
down_revision = '063ef5a541b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.drop_column('address2')
        batch_op.drop_column('address1')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('zip')
        batch_op.drop_column('city')

    with op.batch_alter_table('new_business_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.drop_column('address2')
        batch_op.drop_column('address1')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('zip')
        batch_op.drop_column('city')

    with op.batch_alter_table('update_business_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.drop_column('address2')
        batch_op.drop_column('address1')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('zip')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_business_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('zip', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('address1', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('address2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('address')

    with op.batch_alter_table('new_business_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('zip', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('address1', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('address2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('address')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('zip', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('address1', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('address2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
