"""added sufficient_outlets and accepts_personal_mug to Business class

Revision ID: 91c923ed5c2c
Revises: e69f1dd7ca7e
Create Date: 2023-11-13 17:05:21.758793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c923ed5c2c'
down_revision = 'e69f1dd7ca7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepts_personal_mug', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sufficient_outlets', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('sufficient_outlets')
        batch_op.drop_column('accepts_personal_mug')

    # ### end Alembic commands ###
