"""initial migration

Revision ID: cae62480045f
Revises: 
Create Date: 2023-09-15 14:48:08.152289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cae62480045f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offers_mugs', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wifi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('work_friendly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submitter_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('submitter_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('message_to_admin', sa.Text(), nullable=True))
        batch_op.drop_column('latitude')
        batch_op.drop_column('details')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('details', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('latitude', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('message_to_admin')
        batch_op.drop_column('submitter_email')
        batch_op.drop_column('submitter_name')
        batch_op.drop_column('description')
        batch_op.drop_column('work_friendly')
        batch_op.drop_column('wifi')
        batch_op.drop_column('offers_mugs')

    # ### end Alembic commands ###
